name: CD

on:
  release:
    types: [ published ]

jobs:
  npm-publish:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false

      matrix:
        operating-system: [ ubuntu-latest ]
        node-version: [ 14.x ]

    name: NPM Publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: TypeScript Compiler
        run: npm run build

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
